// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

// ...

await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
);
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5vl3DA2TPs9znYH2_n1_moRuIYyZM_hE',
    appId: '1:443130106444:web:a41e73e84b7d81472d1ae9',
    messagingSenderId: '443130106444',
    projectId: 'crop-mate-sreehari',
    authDomain: 'crop-mate-sreehari.firebaseapp.com',
    storageBucket: 'crop-mate-sreehari.firebasestorage.app',
    measurementId: 'G-CM4SXFJDY0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn9kONuBSnXtHnCNtWX5bbtPLIvNuuFwI',
    appId: '1:806527491969:android:87b975a046ac5ad47c1280',
    messagingSenderId: '806527491969',
    projectId: 'crop-mate-sree',
    storageBucket: 'crop-mate-sree.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKYW-KpNh9_y-z8_BnpskqqTcCwTgn2fM',
    appId: '1:806527491969:ios:c42259a35966fdd17c1280',
    messagingSenderId: '806527491969',
    projectId: 'crop-mate-sree',
    storageBucket: 'crop-mate-sree.firebasestorage.app',
    iosBundleId: 'com.example.cropmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKYW-KpNh9_y-z8_BnpskqqTcCwTgn2fM',
    appId: '1:806527491969:ios:c42259a35966fdd17c1280',
    messagingSenderId: '806527491969',
    projectId: 'crop-mate-sree',
    storageBucket: 'crop-mate-sree.firebasestorage.app',
    iosBundleId: 'com.example.cropmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHKtL7M0Mr6r8AnYzClgOrxq6LgY2Dw6U',
    appId: '1:806527491969:web:81a1ce13be3605807c1280',
    messagingSenderId: '806527491969',
    projectId: 'crop-mate-sree',
    authDomain: 'crop-mate-sree.firebaseapp.com',
    storageBucket: 'crop-mate-sree.firebasestorage.app',
    measurementId: 'G-VF8S990RX3',
  );
}